const chimie = {
    lessons: [
        { title: "Introduction à la Chimie", content: "Contenu de la leçon d'introduction." },
        { title: "Les Atomes", content: "Contenu de la leçon sur les atomes." }
    ],
    exercices: [
        { title: "Exercice sur les atomes", questions: ["Question 1", "Question 2"] },
        { title: "Exercice sur les molécules", questions: ["Question 1", "Question 2"] }
    ],
    quizzes: [
        { title: "Quiz sur l'introduction", questions: ["Q1", "Q2"], answers: ["A1", "A2"] }
    ]
};

export default chimie;
